@host = http://localhost:5000

### Listar todos os pedidos
GET {{host}}/orders

### Criar pedido
POST {{host}}/orders
Content-Type: application/json

{
  "cliente": "Ana Repositório",
  "valor": 250.00
}

### Listar novamente
GET {{host}}/orders

### Buscar pedido específico
GET {{host}}/orders/1

### Buscar pedido inexistente
GET {{host}}/orders/9999