trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET 10 SDK'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*Tests*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore --logger trx --collect:"XPlat Code Coverage"'
      publishTestResults: true

  - task: Docker@2
    displayName: 'Build imagem da API'
    inputs:
      command: 'build'
      Dockerfile: 'OrdersApi/Dockerfile'
      buildContext: 'OrdersApi'
      repository: 'orders-api'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    displayName: 'Build imagem do Web'
    inputs:
      command: 'build'
      Dockerfile: 'OrdersWeb/Dockerfile'
      buildContext: 'OrdersWeb'
      repository: 'orders-web'
      tags: |
        $(Build.BuildId)
        latest